# 请注意，这里的参数是随便写的，只是先占个位置保证格式的正确
# 基于px4的位置环控制器px4_position_controller和速度环控制器px4_velocity_controller共用这一个参数文件

# 是否将文件中的参数同步到飞控中
sync_to_px4: false

# px4 控制环节增益参数
px4_gains:
  # 1. 位置环 (Position Loop)
  position:
    MPC_XY_P: 0.95        # 水平位置比例增益
    MPC_Z_P: 1.0          # 高度位置比例增益

  # 2. 速度环 (Velocity Loop)
  # 后缀 _ACC 表示速度偏差直接映射到期望加速度
  velocity:
    MPC_XY_VEL_P_ACC: 1.8 # 水平速度 P
    MPC_XY_VEL_I_ACC: 0.4 # 水平速度 I (消除静差/风扰)
    MPC_XY_VEL_D_ACC: 0.2 # 水平速度 D (平滑响应)
    MPC_Z_VEL_P_ACC: 4.0  # 垂直速度 P
    MPC_Z_VEL_I_ACC: 2.0  # 垂直速度 I
    MPC_Z_VEL_D_ACC: 0.0  # 垂直速度 D (垂直方向通常 D 为 0)

  # 3. 姿态环 (Attitude Loop)
  # 将角度偏差转换为目标角速度
  attitude:
    MC_ROLL_P: 6.5
    MC_PITCH_P: 6.5
    MC_YAW_P: 2.8

  # 4. 角速率环 (Body Rate Loop)
  # 这里的 K 即为 P 增益
  body_rate:
    roll:
    # 直接调节角速度环的P参数过于危险，这里调节的K参数指的是控制器输出的增益
      MC_ROLLRATE_K: 1.0
      MC_ROLLRATE_I: 0.2
      MC_ROLLRATE_D: 0.003
    pitch:
      MC_PITCHRATE_K: 1.0
      MC_PITCHRATE_I: 0.2
      MC_PITCHRATE_D: 0.003
    yaw:
      MC_YAWRATE_K: 1.0
      MC_YAWRATE_I: 0.1
      MC_YAWRATE_D: 0.0

# 基于px4的速度环控制器额外的增益参数
sunray_velocity_gains:
  position:
    MPC_XY_P: 1.0 
    MPC_XY_I: 0.0
    MPC_XY_D: 0.0
    MPC_Z_P: 1.0 
    MPC_Z_I: 0.0
    MPC_Z_D: 0.0
  settings:
    # 积分分离阈值，当位置偏差过大时，停止积分防止大幅度的超调
    anti_windup_threshold: 2.0
